Repository tempfiles-Team/tempfiles-frontend-v2, pull requests merged in 2023-08, with the labels that each got.

#10 feat: add docker images build and push action
  .github/workflows/docker-image.yaml
  Dockerfile
  nginx.conf
Labels: ✨ 기능, 🐛 버그

#8 feat: add upload options
  package.json
  src/components/common/Button/index.tsx
  src/components/common/Button/styled.ts
  src/components/common/Navbar/styled.ts
  src/components/common/index.ts
  src/components/index.ts
  src/components/layouts/DefaultLayout/index.tsx
  src/components/layouts/DefaultLayout/styled.ts
  src/components/layouts/index.ts
  src/components/main/downloadLimit/index.tsx
  src/components/main/downloadLimit/styled.ts
  src/components/main/expireTime/index.tsx
  src/components/main/expireTime/styled.ts
  src/components/main/index.ts
  src/components/main/optionSection/index.tsx
  src/components/main/optionSection/styled.ts
  src/components/main/password/index.tsx
  src/components/main/password/styled.ts
  src/constant/index.ts
  src/constant/navbar.ts
  src/constant/uploadOptions.ts
  src/pages/index.ts
  src/pages/main/index.tsx
  src/pages/main/styled.ts
  src/styles/colors.ts
  src/styles/global.ts
  tsconfig.eslint.json
  tsconfig.json
  tsconfig.node.json
  yarn.lock
Labels: ✨ 기능, 🎨 디자인

#14 feat: add file upload
  .env.sample
  .eslintrc
  .gitignore
  package.json
  src/App.tsx
  src/api/api.ts
  src/api/file.ts
  src/api/index.ts
  src/components/main/optionSection/styled.ts
  src/components/main/password/styled.ts
  src/constant/uploadOptions.ts
  src/hooks/index.ts
  src/hooks/query/file/index.ts
  src/hooks/query/file/useUploadFile.ts
  src/hooks/query/index.ts
  src/pages/main/index.tsx
  src/pages/main/styled.ts
  src/styles/global.ts
  src/styles/toastify.ts
  src/utils/getFileSize.ts
  src/utils/index.ts
  src/vite-env.d.ts
  yarn.lock
Labels: ✨ 기능

#18 feat: add text upload
  index.html
  package.json
  src/api/api.ts
  src/api/file.ts
  src/api/index.ts
  src/api/text.ts
  src/components/common/Navbar/index.tsx
  src/components/main/downloadLimit/index.tsx
  src/components/main/expireTime/index.tsx
  src/components/main/optionSection/index.tsx
  src/components/main/optionSection/styled.ts
  src/components/main/password/index.tsx
  src/components/main/password/styled.ts
  src/constant/uploadOptions.ts
  src/hooks/query/file/index.ts
  src/hooks/query/file/useUploadFile.ts
  src/hooks/query/index.ts
  src/hooks/query/upload/index.tsx
  src/pages/main/index.tsx
  src/pages/main/styled.ts
  yarn.lock
Labels: ♻️ 리팩토링, ✨ 기능, 🎨 디자인

#22 feat: add detail page
  src/App.tsx
  src/api/api.ts
  src/api/checkPw.ts
  src/api/file.ts
  src/api/index.ts
  src/api/text.ts
  src/assets/index.ts
  src/assets/lockIcon.svg
  src/atom/checkPw.ts
  src/atom/index.ts
  src/components/apiList/ApiBox/index.tsx
  src/components/apiList/index.ts
  src/components/common/Button/index.tsx
  src/components/common/Button/styled.ts
  src/components/common/DataBox/index.tsx
  src/components/common/DataBox/styled.ts
  src/components/common/Password/index.tsx
  src/components/common/Password/styled.ts
  src/components/common/SkeletonUI/index.tsx
  src/components/common/SkeletonUI/styled.ts
  src/components/common/index.ts
  src/components/detail/FileDetails/index.tsx
  src/components/detail/index.ts
  src/components/index.ts
  src/components/layouts/DefaultLayout/styled.ts
  src/components/main/Button/index.tsx
  src/components/main/Button/styled.ts
  src/components/main/DownloadSlider/index.tsx
  src/components/main/DownloadSlider/styled.ts
  src/components/main/ExpireTime/index.tsx
  src/components/main/ExpireTime/styled.ts
  src/components/main/OptionSection/index.tsx
  src/components/main/OptionSection/styled.ts
  src/components/main/index.ts
  src/components/main/optionSection/index.tsx
  src/constant/api.ts
  src/constant/index.ts
  src/hooks/index.ts
  src/hooks/query/checkPw/index.tsx
  src/hooks/query/delete/index.tsx
  src/hooks/query/getItem/index.tsx
  src/hooks/query/index.ts
  src/hooks/query/upload/index.tsx
  src/hooks/useGetInfo.tsx
  src/hooks/useGetWindowSize.ts
  src/pages/api/index.tsx
  src/pages/api/styled.ts
  src/pages/apiList/index.tsx
  src/pages/apiList/styled.ts
  src/pages/checkPw/index.tsx
  src/pages/checkPw/styled.ts
  src/pages/detail/index.tsx
  src/pages/detail/styled.ts
  src/pages/index.ts
  src/pages/main/index.tsx
  src/pages/main/styled.ts
  src/styles/colors.ts
  src/utils/getDay.ts
  src/utils/index.ts
  src/utils/toast.ts
Labels: ✨ 기능, 🎨 디자인

#23 feat: add api page
  src/App.tsx
  src/api/api.ts
  src/components/common/DataBox/styled.ts
  src/constant/api.ts
  src/constant/navbar.ts
  src/pages/index.ts
Labels: ✨ 기능, 🎨 디자인
